# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-01 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
