# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-01 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload01', '0002_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='head',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
