# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-13 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('sex', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
    ]
